export default [
  {
    "name": "Umamageswari K",
    "email": "umaganesh1988@gmail.com",
    "college": "SDNB Vaishnav College For Women",
    "phone": "8939685952",
  },
  {
    "name": "Rohini Aravindan",
    "email": "rohiniaravindan17@gmail.com",
    "college": "Presidency University",
    "phone": "8939074000",
  },
  {
    "name": "T. Sheik Yousuf",
    "email": "sheikres@gmail.com",
    "college": "Mohamed Sathak Engineering College",
    "phone": "9944280680",
  },
  {
    "name": "Bhuvaneshwari R",
    "email": "bhuvi.saakshu@gmail.com",
    "college": "CEG Campus, Anna University",
    "phone": "9092920123",
  },
  {
    "name": "Palanisamy K. C.",
    "email": "kcpesec@gmail.com",
    "college": "Erode Sengunthar Engineering College",
    "phone": "9994311345",
  },
  {
    "name": "Srinivasan M. L",
    "email": "seenaitech@gmail.com",
    "college": "St.Joseph College Of Engineering",
    "phone": "9944159667",
  },
  {
    "name": "S. Raja Shree",
    "email": "rajijce@gmail.com",
    "college": "Sathyabama Institute Of Science And Technology",
    "phone": "09486838080",
  },
  {
    "name": "Valarmathi V",
    "email": "valarskasc1@gmail.com",
    "college": "Sri Krishna Arts And Science College",
    "phone": "8072081885",
  },
  {
    "name": "S. Shunmuga Priya",
    "email": "shun.priya25@gmail.com",
    "college": "Anna University, College Of Engineering Guindy Campus,Chennai",
    "phone": "9677385855",
  },
  {
    "name": "G. K. Moorthy",
    "email": "Gkm5353@gmail.com",
    "college": "Roever Engineering College",
    "phone": "9787871471",
  },
  {
    "name": "Nabeena Ameen",
    "email": "nabeena@crescent.education",
    "college": "B.S Abdur Rahman Crescent Institute Of Science And Technology",
    "phone": "9444206295",
  },
  {
    "name": "Malathy Subramanium",
    "email": "dr.joymalathy@gmail.com",
    "college": "Karpagam Academy Of Higher Education",
    "phone": "9789787465",
  },
  {
    "name": "K Chithra",
    "email": "kkchithracc@gmail.com",
    "college": "SHRIMATHI DEVKUNVAR NANALAL BHATT VAISHNAV COLLEGE FOR WOMEN",
    "phone": "8144178400",
  },
  {
    "name": "K. Antony Sudha",
    "email": "melosudha@gmail.com",
    "college": "Einstein College Of Engineering",
    "phone": "9498499601",
  },
  {
    "name": "M. Nafees Muneera",
    "email": "nafeesmuneera.cse@sathyabama.ac.in",
    "college": "Sathyabama Institute Of Science And Technology",
    "phone": "9840332760",
  },
  {
    "name": "Srabana Pramanik",
    "email": "srabana.edu@gmail.com",
    "college": "Presidency University, Bangalore",
    "phone": "9481136082",
  },
  {
    "name": "Meenakshi L",
    "email": "Meenakshi@kingsedu.ac.in",
    "college": "Kings Engineering College",
    "phone": "08438550458",
  },
  {
    "name": "Syeda Badrunnisa Begum",
    "email": "syedabadrunnisabegum@bitm.edu.in",
    "college": "Ballari Institute Of Technology And Management",
    "phone": "8861821705",
  },
  {
    "name": "Kavya Sree K",
    "email": "kavyasree.k@bitm.edu.in",
    "college": "BITM",
    "phone": "9482880786",
  },
  {
    "name": "Rachel Evangeline Christian",
    "email": "rachel.ec@bitm.edu.in",
    "college": "Ballari Institute Of Technology And Management",
    "phone": "7259430565",
  },
  {
    "name": "M. Ajin",
    "email": "ajin44@gmail.com",
    "college": "St.Xavier's Catholic College Of Engineering",
    "phone": "6381491245",
  },
  {
    "name": "S. Dhandapani",
    "email": "dhandapani@saveetha.ac.in",
    "college": "Saveetha Engineering College",
    "phone": "9865753569",
  },
  {
    "name": "Jaishree Murugesan",
    "email": "jaishree.m@srec.ac.in",
    "college": "Sri Ramakrishna Engineering College",
    "phone": "9489362485",
  },
  {
    "name": "M S Karthika Devi",
    "email": "karthikadevi88@gmail.com",
    "college": "College Of Engineering Guindy Anna University",
    "phone": "9791763413",
  },
  {
    "name": "Jency I",
    "email": "jencypjce@gmail.com",
    "college": "St.Xavier’s Catholic College Of Engineering And Technology",
    "phone": "9952429982",
  },
  {
    "name": "D. Kanchana",
    "email": "kanchand@srmist.edu.in",
    "college": "SRM Institute Of Science And Technology",
    "phone": "9865753562",
  },
  {
    "name": "J. Karthiga",
    "email": "karthiga1785@gmail.com",
    "college": "Thiruthangal Nadar College",
    "phone": "9840427018",
  },
  {
    "name": "Chandrasekhar V",
    "email": "vcs9440971297@gmail.com",
    "college": "BALLARI INSTITUTE OF TECHNOLOGY AND MANAGEMENT",
    "phone": "9440971297",
  },
  {
    "name": "Bharathi S L",
    "email": "bharathi.sl@velammal.edu.in",
    "college": "Velammal Engineering College",
    "phone": "6383211171",
  },
  {
    "name": "C T M Praveen Kumar",
    "email": "ctm.praveen@gmail.com",
    "college": "Ballari Institute Of Technology And Management",
    "phone": "9986219715",
  },
  {
    "name": "R. Rajasekaran",
    "email": "r.rajasekaran@velhightech.com",
    "college":
      "Vel Tech High Tech Dr.Rangarajan Dr.Sakunthala Engineering College",
    "phone": "9842561699",
  },
  {
    "name": "Akila P",
    "email": "akhilaakhila0804@gmail.com",
    "college": "Maha Barathi Engineering College",
    "phone": "9342630250",
  },
  {
    "name": "Gopi G",
    "email": "gopirmd@gmail.com",
    "college": "SIR ISSAC NEWTON COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "phone": "9994503205",
  },
  {
    "name": "T Pandiarajan",
    "email": "pandiarajan.t@ritchennai.edu.in",
    "college": "Rajalakahmi Institute Of Technology",
    "phone": "9943652636",
  },
  {
    "name": "T. Preethiya",
    "email": "preethit3@srmist.edu.in",
    "college": "SRM Institute Of Science And Technology,KTR",
    "phone": "8344477761",
  },
  {
    "name": "Anisha Darathy A",
    "email": "anish16590@gmail.com",
    "college": "Maha Barathi Engineering College",
    "phone": "9994667845",
  },
  {
    "name": "S. Artheeswari",
    "email": "artheeswariit@mailamengg.com",
    "college": "Mailam Engineering College",
    "phone": "9952148842",
  },
  {
    "name": "S. Mohana",
    "email": "mohana-cse@saranathan.ac.in",
    "college": "Saranathan College Of Engineering",
    "phone": "9566470005",
  },
  {
    "name": "Raja S",
    "email": "sk.rajamecse@gmail.com",
    "college": "ADAIKALAMATHA COLLEGE",
    "phone": "7904299461",
  },
  {
    "name": "M. Reena Devi",
    "email": "reenadevi1980@gmail.com",
    "college": "Sri Sarada Niketan College Of Arts And Science For Women",
    "phone": "9894597727",
  },
  {
    "name": "P. Suganthi",
    "email": "suganthi.cse@sairamit.edu.in",
    "college": "Sri Sai Ram Institute Of Technology",
    "phone": "9940291486",
  },
  {
    "name": "R. Saranya",
    "email": "saranyacse28@gmail.com",
    "college": "Aarupadai Veedu Institute Of Technology",
    "phone": "9500021599",
  },
  {
    "name": "Subasri M",
    "email": "subasri.m@trp.srmtrichy.edu.in",
    "college": "SRM TRP ENGINEERING COLLEGE",
    "phone": "8940649481",
  },
  {
    "name": "Priyanga P. T",
    "email": "priyariyapt@gmail.com",
    "college": "PONJESLY COLLEGE OF ENGINEERING",
    "phone": "9626017315",
  },
  {
    "name": "Anitha Julian",
    "email": "cse.anithajulian@gmail.com",
    "college": "Saveetha Engineering College",
    "phone": "6381421225",
  },
  {
    "name": "Ramyadevi R",
    "email": "ramyadeviphd@gmail.com",
    "college": "Saveetha Engineering College",
    "phone": "9629280373",
  },
  {
    "name": "K. Raajasree",
    "email": "kraajasreephd77@gmail.com",
    "college": "Aarupadai Veedu Institute Of Engineering",
    "phone": "8012580135",
  },
  {
    "name": "A. Balkees Bee",
    "email": "balkeesbee.a@trp.srmtrichy.edu.in",
    "college": "SRM TRP Engineering College",
    "phone": "6383910247",
  },
  {
    "name": "Suganya T",
    "email": "suganya.t@trp.srmtrichy.edu.in",
    "college": "SRM TRP ENGINEERING COLLEGE",
    "phone": "9629642266",
  },
  {
    "name": "C Linda",
    "email": "sahayalinda2008@gmail.com",
    "college": "MANONMANIAM SUNDARANAR UNIVERSITY",
    "phone": "9487982623",
  },
  {
    "name": "Sundravadivelu. K",
    "email": "svadiveluk2021@gmail.com",
    "college":
      "Department Of Computer Science, Madurai Kamaraj University, Madurai -21.",
    "phone": "9994008376",
  },
  {
    "name": "S. Titus",
    "email": "drtitus7071@gmail.com",
    "college": "JEPPIAAR ENGINEERING COLLEGE",
    "phone": "9677112443",
  },
  {
    "name": "A. Vidhya",
    "email": "vidhyaraj1988@gmail.com",
    "college": "Jeppiaar Engineering College",
    "phone": "9840187449",
  },
  {
    "name": "A. Muthuraj",
    "email": "muthuraj.a@trp.srmtrichy.edu.in",
    "college": "SRM TRP ENGINEERING COLLEGE",
    "phone": "9486715098",
  },
  {
    "name": "N. Mathangi",
    "email": "mathangi.narayanan04@gmail.com",
    "college": "Meenakshi Sundararajan Engineering College",
    "phone": "9840194394",
  },
  {
    "name": "Yamuna. S",
    "email": "yamunavikramancse@gmail.com",
    "college": "MEENAKSHI SUNDARARAJAN ENGINEERING COLLEGE",
    "phone": "9094825616",
  },
  {
    "name": "Vivek Krishna Rethinavelu",
    "email": "vivekkrishna@jeppiaaruniversity.ac.in",
    "college": "Jeppiaar University",
    "phone": "9790906161",
  },
  {
    "name": "Benjamin Arul S",
    "email": "benjamin@jeppiaaruniversity.ac.in",
    "college": "Jeppiaar University",
    "phone": "9750479501",
  },
  {
    "name": "E Fantin Irudaya Raj",
    "email": "fantinraj@gmail.com",
    "college": "Sivanthi Aditanar College Of Engineering",
    "phone": "9944153473",
  },
  {
    "name": "A. Sathiya",
    "email": "sathya.ai@sairamit.edu.in",
    "college": "Sri Sairam Institute Of Technology",
    "phone": "8760284186",
  },
  {
    "name": "Eesha D",
    "email": "eesha.ece@bmsce.ac.in",
    "college": "B.M.S. College Of Engineering,Bengaluru",
    "phone": "9741690994",
  },
  {
    "name": "Praveena R",
    "email": "praveenaramaswamy@gmail.com",
    "college": "JAISHRIRAM ENGINEERING COLLEGE",
    "phone": "9629583228",
  },
  {
    "name": "Shanmugha Priya R. K.",
    "email": "shanmughapriya.rk@gmail.com",
    "college": "JAI SHRIRAM ENGINEERING COLLEGE",
    "phone": "9487659410",
  },
  {
    "name": "Kayal Vizhi S",
    "email": "kayal0202@gmail.com",
    "college": "PPG Institute Of Technology",
    "phone": "8248952283",
  },
  {
    "name": "Sinu Siva Singh S K",
    "email": "sinu2020@gmail.com",
    "college": "Jeppiaar University",
    "phone": "9787176322",
  },
  {
    "name": "T. Anuja",
    "email": "anuanuja2013@gmail.com",
    "college": "JEPPIAAR Engineering College",
    "phone": "9629285896",
  },
  {
    "name": "Bharanidharan. G",
    "email": "bharanidharan.research@gmail.com",
    "college": "THE NEW COLLEGE, CHENNAI",
    "phone": "9489471234",
  },
  {
    "name": "E Shapna Rani",
    "email": "shapnarulvel@gmail.com",
    "college": "Saranathan College Of Engineering",
    "phone": "9790228613",
  },
  {
    "name": "Pragatheeswari E",
    "email": "epragatheeswari@gmail.com",
    "college": "Kongu Engineering College",
    "phone": "9629790578",
  },
  {
    "name": "Sanchana. R",
    "email": "sanchana.it@sairamit.edu.in",
    "college": "SRI SAI RAM INSTITUTE OF TECHNOLOGY",
    "phone": "7823949388",
  },
  {
    "name": "Lavanya Mathiyalagi A",
    "email": "lavanyamathiyalagi@gmail.com",
    "college": "Einstein College Of Engineering",
    "phone": "9894542652",
  },
  {
    "name": "K. Priyadharshini",
    "email": "priyared7@gmail.com",
    "college": "Jeppiaar Engineering College",
    "phone": "9976333893",
  },
  {
    "name": "Arun G",
    "email": "arungguru@gmail.com",
    "college": "Erode Sengunthar Engineering College. Perundurai, Erode",
    "phone": "9443305553",
  },
  {
    "name": "Lekha P",
    "email": "lekha.cce@sairamit.edu.in",
    "college": "Sri Sai Ram Institute Of Technology",
    "phone": "9952361180",
  },
  {
    "name": "A. Thiripuram",
    "email": "thiripuram82@gmail.com",
    "college": "JEPPIAAR ENGINEERING COLLEGE,CHENNAI",
    "phone": "8754141205",
  },
  {
    "name": "Shakila J",
    "email": "Shakila.1084@gmail.com",
    "college": "Jeppiaar Engineering College",
    "phone": "7010051667",
  },
  {
    "name": "K. Varalakshmi",
    "email": "vk6081@srmist.edu.in",
    "college": "SRM Institute Of Science And Technology",
    "phone": "9710263879",
  },
  {
    "name": "R. Sathiya",
    "email": "sathiyar1@srmist.edu.in",
    "college": "SRMIST VADAPALANI CAMPUS",
    "phone": "9003373906",
  },
  {
    "name": "M Anitha",
    "email": "anithamuthulingam.26@gmail.com",
    "college": "SRM TRP Engineering College, Trichy",
    "phone": "9994531819",
  },
  {
    "name": "D. Sheema",
    "email": "Sheema.d.cse@sathyabama.ac.in",
    "college": "Sathyabama Institute Of Science And Technology",
    "phone": "98405 66351",
  },
  {
    "name": "Rahul. J",
    "email": "r492520@gmail.com",
    "college": "Jeppiaar Engineering College",
    "phone": "7200788825",
  },
  {
    "name": "Satheeswari D",
    "email": "satheeswariyuvarajan@gmail.com",
    "college": "Meenakshi College Of Engineering",
    "phone": "7299252315",
  },
  {
    "name": "Anita Christaline. J.",
    "email": "anitaj@srmist.edu.in",
    "college": "SRM IST VDP",
    "phone": "9444028830",
  },
  {
    "name": "Resmi V",
    "email": "vreshmi15@gmail.com",
    "college": "Mar Ivanios College, Trivandrum",
    "phone": "+919894815748",
  },
  {
    "name": "Allwin D",
    "email": "allwindb@gmail.com",
    "college": "National College , Thiruvananthapuram",
    "phone": "9486955071",
  },
  {
    "name": "Shabnam S",
    "email": "shabnam.sabir@ncas.edu.in",
    "college": "National College, Trivandrum",
    "phone": "9846796005",
  },
  {
    "name": "J. Priya",
    "email": "pria.manikandan@gmail.com",
    "college": "Easwari Engineering College",
    "phone": "9444771290",
  },
  {
    "name": "L. Kannagi",
    "email": "kannagi.cce@sairamit.edu.in",
    "college": "SRI SAIRAM INSTITUTE OF TECHNOLOGY",
    "phone": "9789012489/8072827150",
  },
  {
    "name": "Shifa A H",
    "email": "shifaah5@gmail.com",
    "college": "National College, Trivandrum",
    "phone": "9633980810",
  },
  {
    "name": "Jude Moses Anto Devakanth . J",
    "email": "judedevaj@gmail.com",
    "college": "Manonmaniam Sundaranar University",
    "phone": "9790064200",
  },
  {
    "name": "G . Sunil Vishwa",
    "email": "sunilvishwa200@gmail.com",
    "college": "Achariya Arts And Science",
    "phone": "6385609535",
  },
  {
    "name": "Ragini U",
    "email": "raginiusra8595@gmail.com",
    "college": "National College",
    "phone": "9633398998",
  },
  {
    "name": "J. Anitha",
    "email": "anithaharish78@gmail.com",
    "college": "HINDUSTAN INSTITUE OF TECHNOLOGY AND SCIENCE",
    "phone": "9600110150",
  },
  {
    "name": "K. A. Aswathy",
    "email": "aswathy.ju@gmail.com",
    "college": "St.Xavier's Catholic College Of Engineering,Chunkankadai",
    "phone": "9995141252",
  },
  {
    "name": "K. Vijayalakshmi",
    "email": "Vijayalakshmi.cse@sairamit.edu.in",
    "college": "Sri Sai Ram Institute Of Technology",
    "phone": "8939924719",
  },
  {
    "name": "Jency Rubia J",
    "email": "jencyrubia@gmail.com",
    "college":
      "Vel Tech Rangarajan Dr.Sagunthala R&D Institute Of Science And Technology",
    "phone": "8056417154",
  },
  {
    "name": "Babitha Lincy R",
    "email": "rblincy@gmail.com",
    "college": "Sri Eshwar College Of Engineering",
    "phone": "9597900145",
  },
  {
    "name": "R. Senthamil Selvi",
    "email": "senthamilselvi-cse@saranathan.ac.in",
    "college": "Saranathan College Of Engineering",
    "phone": "9865703131",
  },
  {
    "name": "Prasanth T",
    "email": "tprasanth3@gmail.com",
    "college": "Erode Senguthar Engineering College",
    "phone": "7845400706",
  },
  {
    "name": "Tamilvanan. K",
    "email": "vanan.tamil1983@gmail.com",
    "college": "Erode Sengunthar Engineering College",
    "phone": "9952172237",
  },
  {
    "name": "Ananthy P",
    "email": "ananthyganeshansiva@gmail.com",
    "college": "SRM UNIVERSITY",
    "phone": "9500174505",
  },
  {
    "name": "M. C. Sheeba",
    "email": "sheeba@sxcce.edu.in",
    "college": "St.Xavier's Catholic College Of Engineering",
    "phone": "9486635851",
  },
  {
    "name": "A Saravanan",
    "email": "dean.academic@srmrmp.edu.in",
    "college": "EASWARI ENGINEERING COLLEGE",
    "phone": "9384088563",
  },
  {
    "name": "S. Devipriya",
    "email": "devipriya@jerusalemengg.ac.in",
    "college": "Jerusalem College Of Engineering",
    "phone": "9629800811",
  },
  {
    "name": "Gophika T",
    "email": "gophika.t@eec.srmrmp.edu.in",
    "college": "Easwari Engineering College",
    "phone": "90039 52868",
  },
  {
    "name": "V Sravan Kiran",
    "email": "shravankiran12@gmail.com",
    "college": "VNRVJIET",
    "phone": "8919935694",
  },
  {
    "name": "R Lavanya",
    "email": "lavanyar.aids@sriramec.edu.in",
    "college": "SRIRAM ENGINEERING COLLEGE,PERUMALPATTU",
    "phone": "8248391117",
  },
  {
    "name": "Ramadevi C",
    "email": "ramadevic@stjosephs.ac.in",
    "college": "St.Joseph's College Of Engineering",
    "phone": "9952963763",
  },
  {
    "name": "Lalitha Tb",
    "email": "lalitha.srm@gmail.com",
    "college": "Hindustan Institute Of Technology And Science",
    "phone": "8438301304",
  },
  {
    "name": "Kiran Kumar Nuthalapati",
    "email": "kirankumarbecbapatla@gmail.com",
    "college": "Bapatla Engineering College",
    "phone": "9246972344",
  },
  {
    "name": "P. Jeyalakshmi",
    "email": "jeyalakshmi.mech@hicet.ac.in",
    "college": "Hindusthan College Of Engineering And Technology",
    "phone": "9894496263",
  },
  {
    "name": "Mr. B. B. K. Prasad",
    "email": "bcogbi@gmail.com",
    "college": "Bapatla Engineering College",
    "phone": "+918142527949",
  },
  {
    "name": "Akilandasowmya G",
    "email": "akilandasowmiya.cce@sairamit.edu.in",
    "college": "Sri Sairam Institute Of Technology",
    "phone": "7200022362",
  },
  {
    "name": "D S Lathish Sharan",
    "email": "lathishsharan@gmail.com",
    "college": "Achariya.Arts & Science.College",
    "phone": "8754373784",
  },
  {
    "name": "Sathiyanathan A",
    "email": "shp7974@gmail.com",
    "college": "SRIRAM POLYTECHNIC COLLEGE",
    "phone": "+919789349209",
  },
  {
    "name": "T. Papitha Christobel",
    "email": "papithat@srmist.edu.in",
    "college": "SRM Institute Of Science And Technology Ramapuram Chennai",
    "phone": "7358088516",
  },
  {
    "name": "Vanitha Sheba",
    "email": "vanithasheba@gmail.com",
    "college": "Jerusalem College Of Engineering",
    "phone": "9840938563",
  },
  {
    "name": "Mani Deepak Choudhry",
    "email": "manideepak.c@kgkite.ac.in",
    "college": "KGiSL Institute Of Technology",
    "phone": "9629849186",
  },
  {
    "name": "P. Satyanarayana",
    "email": "satya.sp14@gmail.com",
    "college": "V. R. Siddhartha Engineering College",
    "phone": "8142754240",
  },
  {
    "name": "D. Rasi",
    "email": "rasid@skcet.ac.in",
    "college": "Sri Krishna College Of Engineering And Technology",
    "phone": "9442456604",
  },
  {
    "name": "Suganeswaran R",
    "email": "suganesh.slm@gmail.com",
    "college": "DHIRAJLAL GANDHI COLLEGE OF TECHNOLOGY",
    "phone": "9994086870",
  },
  {
    "name": "Mrs. D. Devi",
    "email": "amuthadurai.d@gmail.com",
    "college": "Maha Barathi Engineering College",
    "phone": "9486502954",
  },
  {
    "name": "S. Santhi",
    "email": "shanthi20111@gmail.com",
    "college": "Valivalam Desikar Polytechnic College",
    "phone": "09943025997",
  },
  {
    "name": "S. Umamaheswari",
    "email": "umamurugesan0104@ gmail.com",
    "college": "P.T. Lee Chengalavrayan Polytechnic College",
    "phone": "8248455355",
  },
  {
    "name": "Ponraj A",
    "email": "ponraj.a@eec.srmrmp.edu.in",
    "college": "Easwari Engineering College",
    "phone": "9884209255",
  },
  {
    "name": "Monisha T",
    "email": "mailonlyformonisha@gmail.com",
    "college": "Jeppiaar Engineering College",
    "phone": "7904886808",
  },
  {
    "name": "K. Selva Sheela",
    "email": "k.selvasheela@gmail.com",
    "college": "KGISL INSTITUTE OF TECHNOLOGY",
    "phone": "9003357208",
  },
  {
    "name": "G Anbu Selvi",
    "email": "g.anbuselvi.be@gmail.com",
    "college": "Sathyabama Institute Of Science And Technology",
    "phone": "9789985395",
  },
  {
    "name": "B. Jeyagowri",
    "email": "jayagowri.chm@hicet.ac.in",
    "college": "Hindusthan College Of Engineering And Technology",
    "phone": "9894245562",
  },
  {
    "name": "Raghul G",
    "email": "raghuldhana@gmail.com",
    "college":
      "SIDDHARTH INSTITUTE OF ENGINEERING & TECHNOLOGY,PUTTUR,ANDHRA PRADESH",
    "phone": "9629745039",
  },
  {
    "name": "Narendran R",
    "email": "narenofficial24@gmail.com",
    "college": "Erode Sengunthar Engineering College",
    "phone": "9944519941",
  },
  {
    "name": "S J Pradeeba",
    "email": "pradeebas.chm@hicet.ac.in",
    "college": "Hindusthan College Of Engineering And Technology",
    "phone": "9942560573",
  },
  {
    "name": "K. B. Ramesh",
    "email": "rameshkb@rvce.edu.in",
    "college": "RV College Of Engineering",
    "phone": "+919342522399",
  },
  {
    "name": "Ch Naga Satish Kumar",
    "email": "nagasatish123@gmail.com",
    "college": "Bapatla Engineering College",
    "phone": "9440110124",
  },
  {
    "name": "K C Aarthi",
    "email": "aarthi@velammal.edu.in",
    "college": "Velammal Engineering College",
    "phone": "09940117264",
  },
  {
    "name": "C. Natesamurthi",
    "email": "cnmoorthi1975@yahoo.com",
    "college":
      "Erode Sengunthar Engineering College, Perundurai,, Erode-638057.",
    "phone": "9790022606",
  },
  {
    "name": "Ramachandran R",
    "email": "ramachandran.r@rajalakshmi.edu.in",
    "college": "Rajalakshmi Engineering College",
    "phone": "9841931099",
  },
  {
    "name": "Bhavani Nimmala",
    "email": "bhavaninimmala86@gmail.com",
    "college": "Bapatla Engineering College",
    "phone": "9292101066",
  },
  {
    "name": "Hamsanandhini S",
    "email": "hamsanandhini@gmail.com",
    "college": "Kongu Engineering College",
    "phone": "8508609209",
  },
  {
    "name": "S. Murugan",
    "email": "murugans@tec-edu.in",
    "college": "Thamirabharani Engineering College",
    "phone": "7550322390",
  },
  {
    "name": "C. Priya",
    "email": "harinikpriya@gmail.com",
    "college": "Siddharth Institute Of Engineering & Technology",
    "phone": "+916369930268",
  },
  {
    "name": "Rohini J",
    "email": "rohiniloganathan10@gmail.com",
    "college": "Erode Sengunthar Engineering College",
    "phone": "7339271717",
  },
  {
    "name": "Tamizharasi Seetharaman",
    "email": "gst30091993@gmail.com",
    "college": "CMR University",
    "phone": "7826860759",
  },
  {
    "name": "Malathi Eswaran",
    "email": "malathieswaran@gmail.com",
    "college": "Kongu Engineering College",
    "phone": "9489373737",
  },
  {
    "name": "K. P. Suresh",
    "email": "sureshkp@skct.edu.in",
    "college": "Sri Krishna College Of Technology, Coimbatore",
    "phone": "9715557330",
  },
  {
    "name": "S. R. Thilagavathy",
    "email": "srthilagavathy99@gmail.com",
    "college": "Jeppiaar Engineering College",
    "phone": "07338794197",
  },
  {
    "name": "Mohamed Mustaq Ahmed. A",
    "email": "mmmustaq@gmail.com",
    "college": "The New College",
    "phone": "7358400393",
  },
  {
    "name": "Nisha Robin Rohit",
    "email": "nisha.r@cmr.edu.in",
    "college": "CMR University(Lakeside Campus), Bangalore",
    "phone": "9677352822",
  },
  {
    "name": "Prema P",
    "email": "premigce@gmail.com",
    "college": "Alpha College Of Engineering",
    "phone": "6369976367",
  },
  {
    "name": "Arivu Selvam B",
    "email": "arivuselvam.b@eec.srmrmp.edu.in",
    "college": "EASWARI ENGINEERING COLLEGE",
    "phone": "9994201384",
  },
  {
    "name": "Kiruthika S",
    "email": "skiruthicse@gmail.com",
    "college": "Erode Sengunthar Engineering College",
    "phone": "9003356800",
  },
  {
    "name": "Resmi R Nair",
    "email": "resmi.gie@gmail.com",
    "college": "Saveetha Engineering College",
    "phone": "9884304311",
  },
  {
    "name": "B. Sasikumar",
    "email": "sasikb2002@gmail.com",
    "college": "Erode Sengunthar Engineering College",
    "phone": "9036064370",
  },
  {
    "name": "Saravanan G",
    "email": "sarapro2005@gmail.com",
    "college": "KPR Institute Of Engineering And Technology",
    "phone": "9655445823",
  },
  {
    "name": "Shanmuga Priya G",
    "email": "priyakailash21@gmail.com",
    "college": "Thamirabharani Engineering College",
    "phone": "9043421710",
  },
  {
    "name": "V C Chandra Shekara",
    "email": "vccc13@gmail.com",
    "college": "P E S College Of Engineering Mandya",
    "phone": "9845603040",
  },
  {
    "name": "R. Senthil Kumar",
    "email": "senthilkumar.ramu@vit.ac.in",
    "college": "Vellore Institute Of Technology,",
    "phone": "9003395360",
  },
  {
    "name": "N Ramya",
    "email": "ramya-cse@saranathan.ac.in",
    "college": "SARANATHAN COLLEGE OF ENGINEERING",
    "phone": "+919566541240",
  },
  {
    "name": "Nirmaladevi. G",
    "email": "nirmaladevi.cse@sairamit.edu.in",
    "college": "SRI SAIRAM INSTITUTE OF TECHNOLOGY",
    "phone": "6381248906",
  },
  {
    "name": "S. Sajithabanu",
    "email": "sajithabanu24@gmail.com",
    "college": "Mohamed Sathak Engineering College",
    "phone": "09043377040",
  },
  {
    "name": "S. Arulmozhi",
    "email": "arul3345@gmail.com",
    "college": "Erode Sengunthar Engineering College, Thudupathi",
    "phone": "9715179345",
  },
  { "name": "", "email": "", "college": "", "phone": "" },
  {
    "name": "H. Hussainiya Fathima",
    "email": "fathimahb201190@gmail.com",
    "college": "Mohamed Sathak Engineering College",
    "phone": "8110930038",
  },
  {
    "name": "B. Karthikeyan",
    "email": "karthikeyanb@skcet.ac.in",
    "college": "SRI KRISHNA COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "phone": "9940966012",
  },
  {
    "name": "Mrs. Shirlin F",
    "email": "shirlinf@gmail.com",
    "college": "Loyola Institute Of Technology And Science",
    "phone": "7708235274",
  },
  {
    "name": "Hoovarththanan B",
    "email": "vbhoovarththanan@gmail.com",
    "college": "Coimbatore Institute Of Technology",
    "phone": "9043351430",
  },
  {
    "name": "S. Meenakshi",
    "email": "meenakss3@srmist.edu.in",
    "college": "SRM IST, Ramapuram, Chennai",
    "phone": "9940465806",
  },
  {
    "name": "Ratna Babu Sadhu",
    "email": "sadhu.ratnababu@gmail.com",
    "college": "Bapatla Engineering College",
    "phone": "9550313992",
  },
  {
    "name": "A Basheer Ahamed",
    "email": "abammb2@gmail.com",
    "college": "Jamal Mohamed College",
    "phone": "9865485833",
  },
  {
    "name": "G. Priyaa Sri , Ap/ai&ds",
    "email": "priyaasrig@gmail.com",
    "college": "MNM JAIN ENGINEERING COLLEGE",
    "phone": "9940993833",
  },
  {
    "name": "B. K. Sivabalan",
    "email": "munnadimuthubalasiva@gmail.com",
    "college": "SRM",
    "phone": "9790291465",
  },
  {
    "name": "Subitha S",
    "email": "subithasatheeshs@gmail.com",
    "college": "ERODE SENGUNTHAR ENGINEERING COLLEGE",
    "phone": "8525092552",
  },
  {
    "name": "R. Shenbagalakshmi",
    "email": "lakshmi.amrith@gmail.com",
    "college":
      "G H Raisoni College Of Engineering And Management, Wagholi,Pune",
    "phone": "9637320055",
  },
  {
    "name": "Narmada B",
    "email": "narmadadgct@gmail.com",
    "college": "DHIRAJLAL GANDHI COLLEGE OF TECHNOLOGY",
    "phone": "9994492294",
  },
  {
    "name": "Mohanavalli M",
    "email": "mohanavalli2007@gmail.com",
    "college": "ERODE SENGUNTHAR ENGINEERING COLLEGE",
    "phone": "8754302544",
  },
  {
    "name": "M. Yasothapriya",
    "email": "yasothapriya2010@gmail.com",
    "college": "Achariya Arts And Science College",
    "phone": "9486070252",
  },
  {
    "name": "P. Deepalakshmi",
    "email": "spdeepalakshmi@gmail.com",
    "college": "Erode Sengunthar Engineering College",
    "phone": "9965175590",
  },
  {
    "name": "Vanitha A",
    "email": "vanithaalagarsamy@gmail.com",
    "college":
      "Vel Tech Multi Tech Dr.Rangarajan Dr.Sakunthala Engineering College",
    "phone": "9486159499",
  },
  {
    "name": "B. Rasina Begum",
    "email": "rasinayousuf@gmail.com",
    "college": "Mohamed Sathak Engineering College",
    "phone": "9944907872",
  },
  {
    "name": "R Shanthi",
    "email": "shanthirmba@esec.ac.in",
    "college": "Erode Sengunthar Engineering College",
    "phone": "8667555064",
  },
  {
    "name": "G. Nirmala",
    "email": "gns.cse@rmd.ac.in",
    "college": "R.M.D Engineering College",
    "phone": "9003059837",
  },
  {
    "name": "K Sivakumar",
    "email": "shivakumar.Phy@hicet.ac.in",
    "college": "Hindusthan College Of Engineering And Technology ,coimbatore.",
    "phone": "9842048708",
  },
  {
    "name": "Senthil Kumaran K",
    "email": "chemsenthilkumaran@gmail.com",
    "college":
      "ERODE SENGUNTHAR ENGINEERING COLLEGE, THUDUPATHI, PERUNDURAI, ERODE.",
    "phone": "9597143496",
  },
  {
    "name": "C. Mallika",
    "email": "gokulmalli2007@gmail.com",
    "college": "E.G.S PILLAY ENGINEERING COLLEGE",
    "phone": "9787650176",
  },
  {
    "name": "R. Kalaivani",
    "email": "kalaivani.r@esec.ac.in",
    "college": "Erode Sengunthar Engineering College",
    "phone": "9788619489",
  },
  {
    "name": "K. Aishwarya",
    "email": "aishu10kanagu@gmail.com",
    "college": "Easwari Engineering College",
    "phone": "6385110931",
  },
  {
    "name": "R Hema",
    "email": "hema.r@eec.srmrmp.edu.in",
    "college": "Easwari Engineering College",
    "phone": "9894480651",
  },
  {
    "name": "Srinarayani K",
    "email": "k.srinarayani22@gmail.com",
    "college": "EASWARI ENGINEERING COLLEGE",
    "phone": "9791138865",
  },
  {
    "name": "Mohamed Rafi M",
    "email": "mdrafi10@gmail.com",
    "college": "Mohamed Sathak Engineering College, Kilakarai",
    "phone": "09442380825",
  },
  {
    "name": "Natarajan P",
    "email": "palanisamynatarajan50@gmail.com",
    "college": "Erode Sengunthar Engineering College",
    "phone": "8637450979",
  },
  {
    "name": "Syed Ahammed Jalalutheen R. B.",
    "email": "profsaj2020@gmail.com",
    "college": "The New College",
    "phone": "9444694826",
  },
  {
    "name": "Nithya P",
    "email": "pnithyame@gmail.com",
    "college": "Government College Of Engineering, Salem",
    "phone": "9786377757",
  },
  {
    "name": "Navaneetha Velammal. M",
    "email": "navaneethavelammalm@saveetha.ac.in",
    "college": "Saveetha Engineering College",
    "phone": "8056896245",
  },
  {
    "name": "P. Tharani",
    "email": "tharani@gcesalem.edu.in",
    "college": "Government College Of Engineering,Salem",
    "phone": "8870215728",
  },
  {
    "name": "M. Idhrees Ahmed",
    "email": "idhreesahmed@thenewcollege.edu.in",
    "college": "The New College, Chennai",
    "phone": "9787178692",
  },
  {
    "name": "Deepti Sharma",
    "email": "deeptisharma@raisoni.net",
    "college": "GHRCEM, Pune",
    "phone": "9404564171",
  },
  {
    "name": "Santhy M",
    "email": "santhym.cse@dgct.ac.in",
    "college": "Dhirajlal Gandhi College Of Technology",
    "phone": "9790585292",
  },
  {
    "name": "Saranya T V",
    "email": "saranyavinayagam92@gmail.com",
    "college": "EASWARI ENGINEERING COLLEGE",
    "phone": "9566028620",
  },
  {
    "name": "Akilagandhi Gs",
    "email": "gsakilagandhi@gmail.com",
    "college": "Easwari Engineering College",
    "phone": "9791035603",
  },
  {
    "name": "Jamal Mohmoodha Bi Fathima. B",
    "email": "jmbfathima@gmail.com",
    "college": "The New College",
    "phone": "8682006799",
  },
  {
    "name": "Malaisamy K",
    "email": "malaisamyphd@gmail.com",
    "college": "Saranathan College Of Engineering",
    "phone": "9655703257",
  },
  {
    "name": "V. P. Krishnamurthy",
    "email": "vpkkalai2010@gmail.com",
    "college": "ERODE SENGUNTHAR ENGINEERING COLLEGE",
    "phone": "9865461948",
  },
  {
    "name": "Anandavel. B",
    "email": "anandavel1977@yahoo.co.in",
    "college": "Government College Of Engineering, Salem",
    "phone": "9944380125",
  },
  {
    "name": "R. Senthamizh Selvi",
    "email": "senthamizhselvi.r@eec.srmrmp.edu.in",
    "college": "EASWARI Engineering College",
    "phone": "9445088477",
  },
  {
    "name": "V. Balaji",
    "email": "vbalaji@crescent.education",
    "college": "B.S.ABDUR RAHMAN CRESCENT INSTITUTE OF SCIENCE & TECHNOLOGY",
    "phone": "9600822007",
  },
  {
    "name": "S. Krithika",
    "email": "krithika650@gmail.com",
    "college": "Easwari Engineering College",
    "phone": "8220476286",
  },
  {
    "name": "Althaf Ahamed. S. A.",
    "email": "althafahamed.cse@dgct.ac.in",
    "college": "Dhirajlal Gandhi College Of Technology",
    "phone": "7299517601",
  },
  {
    "name": "S. P. Valli",
    "email": "vallisp@crescent.education",
    "college": "B.S.Abdur Rahman Crescent Institute Of Science And Technology",
    "phone": "9444152117",
  },
  {
    "name": "G. Venkatesh",
    "email": "venkateshgajendranece@gmail.com",
    "college": "PANIMALAR ENGINEERING COLLEGE",
    "phone": "9710796080",
  },
  {
    "name": "Sabari Ramachandran M",
    "email": "sabarimsecmca@gmail.com",
    "college": "MOHAMED SATHAK ENGINEERING COLLEGE",
    "phone": "98436 73283",
  },
  {
    "name": "V Muthukumar",
    "email": "muthukumar@saveetha.ac.in",
    "college": "Saveetha Engineering College",
    "phone": "9176941555",
  },
  {
    "name": "Janaki Raman S",
    "email": "Janakir@hindustanuniv.ac.in",
    "college": "Hindustan Institute Of Technology And Science",
    "phone": "9840990936",
  },
  {
    "name": "B Meenakshi",
    "email": "Meenakshi.eee@sairam.edu.in",
    "college": "Sri Sairam Engineering College",
    "phone": "89399 23543",
  },
  {
    "name": "R. Sivaprasad",
    "email": "sivaprasad.eee@sairam.edu.in",
    "college": "Sri Sai Ram Engineering College",
    "phone": "9445358356",
  },
  {
    "name": "K. Prathibanandhi",
    "email": "prathibanandhi.eee@sairam.edu.in",
    "college": "Sri Sai Ram Engineering College",
    "phone": "9597817288",
  },
  {
    "name": "Anusha S",
    "email": "anuharisathya@gmail.com",
    "college": "Thamirabharani Engineering College",
    "phone": "9629083362",
  },
  {
    "name": "Manjupriya R",
    "email": "manjupriyar.eee@dgct.ac.in",
    "college": "Dhirajlal Gandhi College Of Technology",
    "phone": "9489244456",
  },
  {
    "name": "G. Sivaperumal",
    "email": "sivaperumalgopalan@gmail.com",
    "college": "Dhirajalal Gandhi College of Technology, Salem",
    "phone": "9578549201",
  },
  {
    "name": "Su. Suganthi",
    "email": "hodai@sairamit.edu.in",
    "college": "Sri Sairam Institute Of Technology",
    "phone": "9962987428",
  },
  {
    "name": "Alima Beevi A",
    "email": "alimabeevia@gmail.com",
    "college": "V. Ramakrishna Polytechnic College",
    "phone": "9677243865",
  },
  {
    "name": "S. Nagarajan",
    "email": "arsnagarajan@gmail.com",
    "college": "Barath Niketan Engineering College",
    "phone": "09443564928",
  },
  {
    "name": "R. Sangeetha Sivakumar",
    "email": "drsangeethasivakumar@gmail.com",
    "college": "Karunya University",
    "phone": "9787040005",
  },
  {
    "name": "A. Shyamala",
    "email": "shyamala.balakumar76@gmail.com",
    "college": "Mohamed Sathak Engineering College",
    "phone": "+919994586271",
  },
  {
    "name": "Nivashini A",
    "email": "namirthappa@gmail.com",
    "college": "Misrimal Navajee Munoth Jain Engineering College",
    "phone": "8056039192",
  },
  {
    "name": "S. Umarani",
    "email": "umashenna@gmail.com",
    "college": "Erode Sengunthar Engineering College",
    "phone": "9688479165",
  },
  {
    "name": "Chellappa. S",
    "email": "pschellappa67@gmail.com",
    "college": "SANKAR POLYTECHNIC COLLEGE (AUTONOMOUS) SANKAR NAGAR",
    "phone": "9442130116",
  },
  {
    "name": "Niyas Ahamed A",
    "email": "niyasahamed62@gmail.com",
    "college": "Thamirabharani Engineering College",
    "phone": "9486889235",
  },
  {
    "name": "Vengatesh Kumar S",
    "email": "ursvenki08@gmail.com",
    "college": "Mohamed Sathak Engineering College",
    "phone": "9994106150",
  },
  {
    "name": "P. Saranya",
    "email": "saranicse@gmail.com",
    "college": "AVS ENGINEERING COLLEGE",
    "phone": "9944297666",
  },
  {
    "name": "X Arputha Rathina",
    "email": "xarathina@crescent.education",
    "college": "B S Abdur Rahman Crescent Institute Of Science And Technology",
    "phone": "9444740794",
  },
  {
    "name": "Navaneethakrishnan",
    "email": "ersnkrishnan1980@gmail.com",
    "college": "ERODE SENGUNTHAR ENGINEERING COLLEGE",
    "phone": "9943810220",
  },
  {
    "name": "M. Shyamalagowri",
    "email": "mshyamalagowri2011@gmail.com",
    "college": "Erode Sengunthar Engineering College",
    "phone": "9842660908",
  },
  {
    "name": "Ambika. K",
    "email": "ambikakavin@gmail.com",
    "college": "AVS ENGINEERING COLLEGE",
    "phone": "9943092027",
  },
  {
    "name": "Sangeetha. K",
    "email": "Sankrish2007@gmail.com",
    "college": "KCG College Of Technology",
    "phone": "9600568719",
  },
  {
    "name": "S Jothi",
    "email": "jothi.cse@kcgcollege.com",
    "college": "KCG College Of Technology",
    "phone": "9840717930",
  },
  {
    "name": "Leninisha Shanmugam",
    "email": "leninisha.shanmugam@vit.ac.in",
    "college": "Vellore Institute Of Technology",
    "phone": "09840546118",
  },
  {
    "name": "Shahana",
    "email": "shahanamani2013@gmail.com",
    "college": "Mohamed Sathak Engineering College",
    "phone": "7639506001",
  },
  {
    "name": "V. Malathi",
    "email": "malathiraj0595@gmail.com",
    "college": "Aarupadai Veedu Institute Of Technology",
    "phone": "9597382802",
  },
  {
    "name": "S Uma Maheswari",
    "email": "umamaheswari.s@eec.srmrmp.edu.in",
    "college": "Easwari Engineering College",
    "phone": "9842172861",
  },
  {
    "name": "Lily Evangelin D",
    "email": "meetevangel@gmail.com",
    "college": "Loyola Institute Of Technology And Science",
    "phone": "9443500560",
  },
  {
    "name": "G. S. Satheesh Kumar",
    "email": "gssatheeshkumar@gmail.com",
    "college": "Erode Sengunthar Engineering College",
    "phone": "9843851898",
  },
  {
    "name": "R Priya",
    "email": "drpriya.snh@rmd.ac.in",
    "college": "R.M.D. Engineering College",
    "phone": "8925413197",
  },
  {
    "name": "Balasubramanian N",
    "email": "mugavaibala@gmail.com",
    "college": "Mohamed Sathak Engineering College, Kilakarai",
    "phone": "9791919703",
  },
  {
    "name": "U. Gowri Sankar",
    "email": "gowriesec2020@gmail.com",
    "college": "ERODE SENGUNTHAR ENGINEERING COLLEGE",
    "phone": "8122003727",
  },
  {
    "name": "G. Valarmathi",
    "email": "valarmathi.ece@sairamit.edu.in",
    "college": "Sri Sai Ram Institute Of Technology",
    "phone": "09789992329",
  },
  {
    "name": "K Sudha",
    "email": "sudhak14@gmail.com",
    "college": "R M D Engineering College",
    "phone": "07702272646",
  },
  {
    "name": "S. Sudha",
    "email": "sudha.s@eec.srmrmp.edu.in",
    "college": "Easwari Engineering College",
    "phone": "9840138070",
  },
  {
    "name": "A. Sathishkumar",
    "email": "sat090579gmail.com",
    "college": "Erode Sengunthar Engineering College",
    "phone": "9994414629",
  },
  {
    "name": "Diana D C",
    "email": "diana.d@eec.srmrmp.edu.in",
    "college": "Easwari Engineering College",
    "phone": "9600104153",
  },
  {
    "name": "S. Subbaiah",
    "email": "subbuvicas@gmail.com",
    "college": "Srm Institute Of Science And Technology",
    "phone": "9443956026",
  },
  {
    "name": "M. Deepak Kumar",
    "email": "deepakkumar@gcesalem.edu.in",
    "college": "Government College Of Engineering, Salem-11",
    "phone": "9500648662",
  },
  {
    "name": "Suthanthiradevi P",
    "email": "devisaran2004@gmail.com",
    "college": "St. Josephs College Of Engineering",
    "phone": "9444459673",
  },
  {
    "name": "P. Karthikeyan",
    "email": "carthikn.p@gmail.com",
    "college": "Erode Sengunthar Engineering College",
    "phone": "9944363743",
  },
  {
    "name": "Indumathy P",
    "email": "indumathyp@gmail.com",
    "college": "Easwari Engineering College",
    "phone": "09962001729",
  },
  {
    "name": "P Sudha",
    "email": "sudhapubgl@gmail.com",
    "college":
      "Presidency University, Itgalpur Rajanakunte, Yelahanka, Bengaluru",
    "phone": "9840052696",
  },
  {
    "name": "Devimani M S",
    "email": "devimanikarunakaran@gmail.com",
    "college": "Erode Sengunthar Engineering College",
    "phone": "9942895716",
  },
  {
    "name": "K. Akil",
    "email": "civilhod@hicet.ac.in",
    "college": "Hindusthan College Of Engineering And Technology, Coimbatore",
    "phone": "9894094930",
  },
  {
    "name": "Shiny Duela J",
    "email": "shinyduj@srmist.edu.in",
    "college": "SRM Institute Of Science And Technology, Ramapuram Campus",
    "phone": "9962560567",
  },
  {
    "name": "Meena Kumari K S",
    "email": "meena.kks@gmail.com",
    "college": "Presidency University",
    "phone": "9620614944",
  },
  {
    "name": "S. Vanaja",
    "email": "vanaja.s@eec.srmrmp.edu.in",
    "college": "Easwari Engineering College",
    "phone": "9094866634",
  },
  {
    "name": "Preeti Verma",
    "email": "preetiverma@crescent.education",
    "college": "BS Abdur Rahman Crescent Institute Of Science And Engineering",
    "phone": "9773570748",
  },
  {
    "name": "R. Akila",
    "email": "rakila@crescent.education",
    "college": "B.S.A.Crescent Institute Of Science And Technology",
    "phone": "9952306094",
  },
  {
    "name": "C Vijayalakhsmi",
    "email": "vijayalakshmi@crescent.education",
    "college": "B S Abdur Rahman Crescent Institute Of Science And Technology",
    "phone": "9840489748",
  },
  {
    "name": "C. Hema",
    "email": "hemac@crescent.education",
    "college": "B.S.Abdur Rahman Crescent Institute Of Science And Technology",
    "phone": "7397463890",
  },
  {
    "name": "K Ramesh",
    "email": "Rameshk.me@gmail.com",
    "college": "Sri Krishna College Of Engineering And Technology",
    "phone": "9842012421",
  },
  {
    "name": "A Radhika",
    "email": "radhika.a@crescent.education",
    "college": "B S Abdur Rahman Crescent Institute Of Science And Technology",
    "phone": "9677017303",
  },
  {
    "name": "Kasthuri C",
    "email": "kasthuriesec@gmail.com",
    "college": "Erode Sngunthar Enginering College,Perundurai.",
    "phone": "+919865220972",
  },
  {
    "name": "S Maheswari",
    "email": "mahesiva1712@gmail.com",
    "college": "Dhirajlal Gandhi College Of Technology",
    "phone": "7708439581",
  },
  {
    "name": "J. Brindha Merin",
    "email": "brindhamerin@gmail.com",
    "college": "B.S.Abdur Rahman Crescent Institute Of Science And Technology",
    "phone": "9445201995",
  },
  {
    "name": "S. Dhanalakshmi",
    "email": "ssdhanalakshmi@gmail.com",
    "college": "Government College Of Engineering, Salem-11",
    "phone": "9841646822",
  },
  {
    "name": "S. Thanga Ramya",
    "email": "thangaramya@gmail.com",
    "college": "R.M.K.Engineering College",
    "phone": "9791033144",
  },
  {
    "name": "Niyati Kumari Behera",
    "email": "niyati@crescent.education",
    "college": "BSAR Crescent Institute Of Science And Technology",
    "phone": "9840950469",
  },
  {
    "name": "B Dhanalakshmi",
    "email": "dhanalakshmi@crescent.education",
    "college": "B.S Abdur Rahman Crescent Institute Of Science And Technology",
    "phone": "9940024534",
  },
  {
    "name": "Antony Asir Daniel V",
    "email": "asirdaniel1984@gmail.com",
    "college": "Loyola Institute Of Technology And Science",
    "phone": "9943143815",
  },
  {
    "name": "Prof. K. Manimala",
    "email": "manimalaaks@gmail.com",
    "college": "Government College Of Engineering, Salem-11",
    "phone": "9442529413",
  },
  {
    "name": "K. Malathi",
    "email": "malathisaravanan2015@gmail.com",
    "college": "Saveetha Engineering College",
    "phone": "9444749975",
  },
  {
    "name": "D. Madhina Banu",
    "email": "madina@crescent.education",
    "college": "BSA Crescent Institute Of Science And Technology",
    "phone": "8939941943",
  },
  {
    "name": "V. Muthupriya",
    "email": "muthupriya@crescent.education",
    "college": "B.S.Abdur Rahman Crescent Institute Of Science And Technology",
    "phone": "9841862224",
  },
  {
    "name": "P Hemavathy",
    "email": "hemamanigandan@gmail.com",
    "college": "Saveetha Engineering College",
    "phone": "9566066222",
  },
  {
    "name": "S. K. Indumathi",
    "email": "skindumathi@hindustanuniv.ac.in",
    "college": "Hindustan Institute Of Technology And Science, Chennai",
    "phone": "9994183300",
  },
  {
    "name": "Archana U",
    "email": "aau.csd@rmkec.ac.in",
    "college": "RMK ENGINEERING COLLEGE",
    "phone": "9360188379",
  },
  {
    "name": "A. Snegaa",
    "email": "snegaa@crescent.education",
    "college": "B.S Abdur Rahman Crescent Institute Of Science And Technology",
    "phone": "9344037813",
  },
  {
    "name": "Sudha Rajesh",
    "email": "drsudharajesh84@gmail.com",
    "college": "SRMIST - KTR Campus",
    "phone": "9445959163",
  },
  {
    "name": "Nithyanandam C",
    "email": "nithyanandam.mech@hicet.ac.in",
    "college": "Hindusthan College Of Engineering And Technology, Coimbatore",
    "phone": "9092280022",
  },
  {
    "name": "Priyadharshini S",
    "email": "smart.priyasuresh@gmail.com",
    "college": "P. T. Lee C. N. P. T COLLEGE",
    "phone": "09840125694",
  },
  {
    "name": "S. Mahalakshmi",
    "email": "smi.csd@rmkec.ac.in",
    "college": "R.M.K. Engineering College",
    "phone": "7305774999",
  },
  {
    "name": "Satish Srinivas S",
    "email": "cengsatish@gmail.com",
    "college": "Easwari Engineering College",
    "phone": "9940668210",
  },
  {
    "name": "M Beula Kutti",
    "email": "bm3895@srmist.edu.in",
    "college": "SRMIST",
    "phone": "7358200646",
  },
  {
    "name": "Leninpugalhanthi P",
    "email": "leninpugal@skct.edu.in",
    "college": "Sri Krishna College Of Technology",
    "phone": "9629458595",
  },
  {
    "name": "S. Revathi",
    "email": "revathisathiya2202@gmail.com",
    "college": "B.S.Abdur Rahman Crescent Institute Of Science And Technology",
    "phone": "9445661179",
  },
  {
    "name": "K. Valarmathi",
    "email": "valarmathi.k@vit.ac.in",
    "college": "Vellore Institute Of Technology",
    "phone": "9940143964",
  },
  {
    "name": "Jihad Aboobaker",
    "email": "jihadabubacker@gmail.com",
    "college": "Pondicherry Technological University",
    "phone": "9496336660",
  },
  {
    "name": "N Padmavathy",
    "email": "padmajeppiaarcollege@gmail.com",
    "college": "Jeppiaar University",
    "phone": "9176742258",
  },
  {
    "name": "S Sudha Mercy",
    "email": "ssm.csd@rmkec.ac.in",
    "college": "R.M.K. Engineering College",
    "phone": "9566095403",
  },
  {
    "name": "Nandhagopal S",
    "email": "nandhagopal.s@kpriet.ac.in",
    "college": "KPR Institute Of Engineering And Technology",
    "phone": "9787677167",
  },
  {
    "name": "Rajeshkumar S",
    "email": "suyamburajesh@gmail.com",
    "college": "KPR Institute Of Engineering And Technology",
    "phone": "9751965146",
  },
  {
    "name": "Kothai G",
    "email": "kothai.g@kpriet.ac.in",
    "college": "KPR Institute Of Engineering And Technology",
    "phone": "9677660531",
  },
  {
    "name": "R Swetha",
    "email": "swethar@francisxavier.ac.in",
    "college": "Francis Xavier Engineering College",
    "phone": "8764940911",
  },
  {
    "name": "Bency P Emmanuel",
    "email": "bency1193@gmail.com",
    "college": "Francis Xavier Engineering College, Tirunelveli",
    "phone": "7708646006",
  },
  {
    "name": "M. Renisha",
    "email": "renisha@francisxavier.ac.in",
    "college": "Francis Xavier Engineering College",
    "phone": "7598146625",
  },
  {
    "name": "S. Maheswari",
    "email": "rs.mahes17@gmail.com",
    "college": "Easwari Engineering College",
    "phone": "9884443567",
  },
  {
    "name": "Francis Lwesya",
    "email": "flwesya@yahoo.com",
    "college": "The Maharaja Sayajirao University Of Baroda",
    "phone": "9081487765",
  },
  {
    "name": "Arshiya Mobeen M",
    "email": "arshiyamobeen@gmail.com",
    "college": "JEPPIAAR ENGINEERING COLLEGE",
    "phone": "9884946867",
  },
  {
    "name": "S. Sivakumar",
    "email": "sivaskumarmca@gmail.com",
    "college": "SRMIST Ramapuram Campus Chennai",
    "phone": "9597779776",
  },
  {
    "name": "S. Sharonpriya",
    "email": "sharonpriya2004@gmail.com",
    "college": "B.S Abdur Rahman Crescent Nstitute Of Science And Technology",
    "phone": "9600016318",
  },
  {
    "name": "G Ginni",
    "email": "ginnimuthuvel@gmail.com",
    "college": "Francis Xavier Engineering College",
    "phone": "9942491180",
  },
  {
    "name": "P. Preethika",
    "email": "preethika.mnm@gmail.com",
    "college": "Misrimal Navajee Munoth Jain Engineering College, Chennai",
    "phone": "8939013662",
  },
  {
    "name": "B. Vinodhini,",
    "email": "profbvinodhini1975@gmail.com",
    "college": "SNS College Of Technology, Coimbatore",
    "phone": "9940985448",
  },
  {
    "name": "Anandhi",
    "email": "anandhimaya@gmail.com",
    "college": "AVS ENGINEERING COLLEGE",
    "phone": "8825959510",
  },
  {
    "name": "N. Suma",
    "email": "sumasivaravi@gmail.com",
    "college": "Karpagam Institute Of Technology",
    "phone": "8489223255",
  },
  {
    "name": "M. Sathiya Priya",
    "email": "sathia.ece@karpagamtech.ac.in",
    "college": "Karpagam Institute Of Technology",
    "phone": "91594 66284",
  },
  {
    "name": "Asha Shendge",
    "email": "asha.shendge@raisoni.net",
    "college": "G H Raisoni College Of Engineering And Management Pune",
    "phone": "9834019726",
  },
  {
    "name": "P. Sureshkumar",
    "email": "psureshvijayan2121@gmail.com",
    "college": "Erode Sengunthar Engineering College -- Perundurai.",
    "phone": "9865257887",
  },
  {
    "name": "Bindu Babu",
    "email": "bindu.k@eec.srmrmp.edu.in",
    "college": "Easwari Engineering College",
    "phone": "9566159859",
  },
  {
    "name": "Sangeetha. K",
    "email": "sankrish2007 @gmail.com",
    "college": "KCG College Of Technology",
    "phone": "9600568719",
  },
  {
    "name": "Ms. K. Abirami",
    "email": "abirami.k@eec.srmrmp.edu.in",
    "college": "Easwari Engineering College",
    "phone": "9840803070",
  },
  {
    "name": "D. Jessintha",
    "email": "jessintha.d@eec.srmrmp.edu.in",
    "college": "Easwari Engineering College",
    "phone": "9566002939",
  },
  {
    "name": "K. Rahimunnisa",
    "email": "rahimunnisa.k@eec.srmrmp.edu.in",
    "college": "Easwari Engineering College",
    "phone": "7339220736",
  },
  {
    "name": "Anita Titus",
    "email": "anitatitus72@gmail.com",
    "college": "Jeppiaar University",
    "phone": "",
  },
  {
    "name": "Ajith Kumar S",
    "email": "ajithkumareduclg@gmail.com",
    "college": "Stella Mary's College Of Engineering,Nagercoil.",
    "phone": "9943379750",
  },
  {
    "name": "A Alif Siddiqua Begam",
    "email": "alifsiddiquabegum@crescent.education",
    "college":
      "B.S. Abdur Rahman Crescent Institute Of Science And Technology, Chennai",
    "phone": "",
  },
  {
    "name": "N. Sabiyath Fathima",
    "email": "sabiyathfathima@crescent.education",
    "college":
      "B.S. Abdur Rahman Crescent Institute Of Science And Technology, Chennai",
    "phone": "9840507477",
  },
  {
    "name": "Thanikaivel Murugan D",
    "email": "thanikaivel.d@gmail.com",
    "college": "Jeppiaar Engineering College",
    "phone": "8825567716",
  },
  {
    "name": "R. Kalpana",
    "email": "kalpanar.ece25@gmail.com",
    "college": "VELTECH MULTITECH",
    "phone": "9629501470",
  },
  {
    "name": "M. Tamilselvi",
    "email": "tamilchid@gmail.com",
    "college": "Erode Sengunthar Engineering College (Autonomous),",
    "phone": "96006 74090",
  },
  {
    "name": "Haston Amit Kumar",
    "email": "haston2009@gmail.com",
    "college": "Jeppiaar Engineering College",
    "phone": "9791010701",
  },
  {
    "name": "R. Kandavel",
    "email": "krkandavel@gmail.com",
    "college": "Jeppiar School Of Management",
    "phone": "9698965123",
  },
  {
    "name": "G. Kanagavalli",
    "email": "kanagavalli.ece@bharathuniv.ac.in",
    "college": "Bharath Institute Of Higher Education And Research",
    "phone": "9551485989",
  },
  {
    "name": "Resmi V",
    "email": "vreshmi15@gmail.com",
    "college": "Mar Ivanios College, Trivandrum",
    "phone": "+919894815748",
  },
  {
    "name": "V C Chandra Shekara",
    "email": "vccc13@gmail.com",
    "college": "P E S College Of Engineering Mandya",
    "phone": "9845603040",
  },
  {
    "name": "G. Valarmathi",
    "email": "valarmathi.ece@sairamit.edu.in",
    "college": "Sri Sai Ram Institute Of Technology",
    "phone": "09789992329",
  },
  {
    "name": "N. Suma",
    "email": "sumasivaravi@gmail.com",
    "college": "Karpagam Institute Of Technology",
    "phone": "8489223255",
  },
  {
    "name": "M. Sathiya Priya",
    "email": "sathia.ece@karpagamtech.ac.in",
    "college": "Karpagam Institute Of Technology",
    "phone": "91594 66284",
  },
  {
    "name": "Bindu Babu",
    "email": "bindu.k@eec.srmrmp.edu.in",
    "college": "Easwari Engineering College",
    "phone": "9566159859",
  },
  {
    "name": "Antony Asir Daniel V",
    "email": "asirdaniel1984@gmail.com",
    "college": "Loyola Institute Of Technology And Science",
    "phone": "9943143815",
  },
  {
    "name": "K. Malathi",
    "email": "malathisaravanan2015@gmail.com",
    "college": "Saveetha Engineering College",
    "phone": "9444749975",
  },
  {
    "name": "P Hemavathy",
    "email": "hemamanigandan@gmail.com",
    "college": "Saveetha Engineering College",
    "phone": "9566066222",
  },
  {
    "name": "Jihad Aboobaker",
    "email": "jihadabubacker@gmail.com",
    "college": "Pondicherry Technological University",
    "phone": "9496336660",
  },
  {
    "name": "N Padmavathy",
    "email": "padmajeppiaarcollege@gmail.com",
    "college": "Jeppiaar University",
    "phone": "9176742258",
  },
  {
    "name": "Ms. K. Abirami",
    "email": "abirami.k@eec.srmrmp.edu.in",
    "college": "Easwari Engineering College",
    "phone": "9840803070",
  },
  {
    "name": "D. Jessintha",
    "email": "jessintha.d@eec.srmrmp.edu.in",
    "college": "Easwari Engineering College",
    "phone": "9566002939",
  },
  {
    "name": "Thanikaivel Murugan D",
    "email": "thanikaivel.d@gmail.com",
    "college": "Jeppiaar Engineering College",
    "phone": "8825567716",
  },
  {
    "name": "R. Kalpana",
    "email": "kalpanar.ece25@gmail.com",
    "college": "VELTECH MULTITECH",
    "phone": "9629501470",
  },
  {
    "name": "Haston Amit Kumar",
    "email": "haston2009@gmail.com",
    "college": "Jeppiaar Engineering College",
    "phone": "9791010701",
  },
  {
    "name": "R. Kandavel",
    "email": "krkandavel@gmail.com",
    "college": "Jeppiar School Of Management",
    "phone": "9698965123",
  },
  {
    "name": "Name Of The Participants (same As To Appear On Your Certificate)",
    "email":
      "Enter your Email Address(Link for participation will be sent to this ID)",
    "college": "Enter The College Name",
    "phone": "Contact Number (WhatsApp No)",
  },
  {
    "name": "Umamageswari K",
    "email": "umaganesh1988@gmail.com",
    "college": "SDNB Vaishnav College For Women",
    "phone": "8939685952",
  },
  {
    "name": "Rohini Aravindan",
    "email": "rohiniaravindan17@gmail.com",
    "college": "Presidency University",
    "phone": "8939074000",
  },
  {
    "name": "Srabana Pramanik",
    "email": "srabana.edu@gmail.com",
    "college": "Presidency University, Bangalore",
    "phone": "9481136082",
  },
  {
    "name": "E Fantin Irudaya Raj",
    "email": "fantinraj@gmail.com",
    "college": "Sivanthi Aditanar College Of Engineering",
    "phone": "9944153473",
  },
  {
    "name": "Eesha D",
    "email": "eesha.ece@bmsce.ac.in",
    "college": "B.M.S. College Of Engineering,Bengaluru",
    "phone": "9741690994",
  },
  {
    "name": "K. Varalakshmi",
    "email": "vk6081@srmist.edu.in",
    "college": "SRM Institute Of Science And Technology",
    "phone": "9710263879",
  },
  {
    "name": "K. Vijayalakshmi",
    "email": "Vijayalakshmi.cse@sairamit.edu.in",
    "college": "Sri Sai Ram Institute Of Technology",
    "phone": "8939924719",
  },
  {
    "name": "Mani Deepak Choudhry",
    "email": "manideepak.c@kgkite.ac.in",
    "college": "KGiSL Institute Of Technology",
    "phone": "9629849186",
  },
  {
    "name": "D. Rasi",
    "email": "rasid@skcet.ac.in",
    "college": "Sri Krishna College Of Engineering And Technology",
    "phone": "9442456604",
  },
  {
    "name": "S. Murugan",
    "email": "murugans@tec-edu.in",
    "college": "Thamirabharani Engineering College",
    "phone": "7550322390",
  },
  {
    "name": "Shanmuga Priya G",
    "email": "priyakailash21@gmail.com",
    "college": "Thamirabharani Engineering College",
    "phone": "9043421710",
  },
  {
    "name": "P. Preethika",
    "email": "preethika.mnm@gmail.com",
    "college": "Misrimal Navajee Munoth Jain Engineering College, Chennai",
    "phone": "8939013662",
  },
  {
    "name": "A Basheer Ahamed",
    "email": "abammb2@gmail.com",
    "college": "Jamal Mohamed College",
    "phone": "9865485833",
  },
  {
    "name": "V J Chakravarthy",
    "email": "chakkucksm1808@gmail.com",
    "college": "Dr. MGR Educational And Research Institute",
    "phone": "9883161687",
  },
  {
    "name": "Anusha S",
    "email": "anuharisathya@gmail.com",
    "college": "Thamirabharani Engineering College",
    "phone": "9629083362",
  },
  {
    "name": "Niyas Ahamed A",
    "email": "niyasahamed62@gmail.com",
    "college": "Thamirabharani Engineering College",
    "phone": "9486889235",
  },
  {
    "name": "Sangeetha. K",
    "email": "Sankrish2007@gmail.com",
    "college": "KCG College Of Technology",
    "phone": "9600568719",
  },
  {
    "name": "S Jothi",
    "email": "jothi14.baskar@gmail.com",
    "college": "KCG College Of Technology",
    "phone": "9840717930",
  },
  {
    "name": "Leninisha Shanmugam",
    "email": "leninisha.shanmugam@vit.ac.in",
    "college": "Vellore Institute Of Technology",
    "phone": "09840546118",
  },
  {
    "name": "Indumathy P",
    "email": "indumathyp@gmail.com",
    "college": "Easwari Engineering College",
    "phone": "09962001729",
  },
  {
    "name": "Meena Kumari K S",
    "email": "meena.kks@gmail.com",
    "college": "Presidency University",
    "phone": "9620614944",
  },
  {
    "name": "B. Vinodhini,",
    "email": "profbvinodhini1975@gmail.com",
    "college": "SNS College Of Technology, Coimbatore",
    "phone": "9940985448",
  },
  {
    "name": "Anandhi",
    "email": "anadhimaya@gmail.com",
    "college": "AVS ENGINEERING COLLEGE",
    "phone": "8825959510",
  },
  {
    "name": "K Ramesh",
    "email": "Rameshk.me@gmail.com",
    "college": "Sri Krishna College Of Engineering And Technology",
    "phone": "9842012421",
  },
  {
    "name": "V. Muthupriya",
    "email": "muthupriya@crescent.education",
    "college": "B.S.Abdur Rahman Crescent Institute Of Science And Technology",
    "phone": "9841862224",
  },
  {
    "name": "Nandhagopal S",
    "email": "nandhagopal.s@kpriet.ac.in",
    "college": "KPR Institute Of Engineering And Technology",
    "phone": "9787677167",
  },
  {
    "name": "Rajeshkumar S",
    "email": "suyamburajesh@gmail.com",
    "college": "KPR Institute Of Engineering And Technology",
    "phone": "9751965146",
  },
  {
    "name": "Kothai G",
    "email": "kothai.g@kpriet.ac.in",
    "college": "KPR Institute Of Engineering And Technology",
    "phone": "9677660531",
  },
  {
    "name": "S. Maheswari",
    "email": "rs.mahes17@gmail.com",
    "college": "Easwari Engineering College",
    "phone": "9884443567",
  },
  {
    "name": "S. Subbaiah",
    "email": "subbuvicas@gmail.com",
    "college": "Srm Institute Of Science And Technology",
    "phone": "9443956026",
  },
  {
    "name": "Arshiya Mobeen M",
    "email": "arshiyamobeen@gmail.com",
    "college": "JEPPIAAR ENGINEERING COLLEGE",
    "phone": "9884946867",
  },
  {
    "name": "S. Sivakumar",
    "email": "sivaskumarmca@gmail.com",
    "college": "SRMIST Ramapuram Campus Chennai",
    "phone": "9597779776",
  },
  {
    "name": "A Alif Siddiqua Begam",
    "email": "alifsiddiquabegum@crescent.education",
    "college":
      "B.S. Abdur Rahman Crescent Institute Of Science And Technology, Chennai",
    "phone": "",
  },
  {
    "name": "M. Tamilselvi",
    "email": "tamilchid@gmail.com",
    "college": "Erode Sengunthar Engineering College (Autonomous),",
    "phone": "96006 74090",
  },
  {
    "name": "G. Kanagavalli",
    "email": "kanagavalli.ece@bharathuniv.ac.in",
    "college": "Bharath Institute Of Higher Education And Research",
    "phone": "9551485989",
  },
  {
    "name": "V Archana",
    "email": "archanaveera88@gmail.com",
    "college": "Tagore Engineering College",
    "phone": "9445090253",
  },
  {
    "name": "T. Kalai Selvi",
    "email": "tkalaiselvi1281@gmail.com",
    "college": "Erode Sengunthar Engineering College",
    "phone": "9842899992",
  },
  {
    "name": "Ms. K. Abirami",
    "email": "abirami.k@eec.srmrmp.edu.in",
    "college": "Easwari Engineering College",
    "phone": "9840803070",
  },
  {
    "name": "Janaki Raman S",
    "email": "janakir@hindustanuniv.ac.in",
    "college": "Hindustan Institute Of Technology And Science",
    "phone": "9840990936",
  },
  {
    "name": "S. Hemalatha",
    "email": "hemaaptc@gmail.com",
    "college": "Tagore Engineering College",
    "phone": "9176256630",
  },
  {
    "name": "S. Shobana",
    "email": "shob.jsh@gmail.com",
    "college": "Tagore Engineering College",
    "phone": "8825788634",
  },
  {
    "name": "V. Antony Asir Daniel",
    "email": "asirdaniel1984@gmail.com",
    "college": "Loyola Institute Of Technology & Science,",
    "phone": "9943143815",
  },
  {
    "name": "T Porselvi",
    "email": "porselvi.eee@sairam.edu.in",
    "college": "Sri Sairam Engineering College",
    "phone": "7904700026",
  },
  {
    "name": "I Karthiga",
    "email": "karthiga.cse@crescent.education",
    "college": "B S Abdur Rahman Crescent Institute of Science & Technology",
    "phone": "<>",
  },
  {
    "name": "K Subashini",
    "email": "subashini1509@gmail.com",
    "college": "Tagore Engineering College",
    "phone": "9003805069",
  },
  {
    "name": "L Vidhya",
    "email": "vidhya.chm@hicet.ac.in",
    "college": "Hindustan College of Engineering & Technology",
    "phone": "9443938568",
  },
  {
    "name": "Niranjan Babu",
    "email": "niranjanbabu2003@gmail.com",
    "college": "Bapatla Engineering College",
    "phone": "9440242535",
  },
  {
    "name": "Priti Rishi",
    "email": "pritir@srmist.edu.in",
    "college": "SRM Institute of Science & Technology, Vadapalani",
    "phone": "<>",
  },
  {
    "name": "Y Robinson",
    "email": "yrobin1969@gmail.com",
    "college": "Erode Sengunthar Engineering College",
    "phone": "9865062970",
  },/*
  {
    "name": "G Najeeb Ahmed",
    "email": "gnajeeb@rediffmail.com",
    "college": "The New College, Chennai",
    "phone": "9840091031",
  },*/
  {
    "name": "Narmadha P G",
    "email": "gnajeeb@rediffmail.com",
    "college": "Panimalar Engineering College",
    "phone": "9840091031",
  },
];
